#!/bin/bash -e

zm_path=$(readlink -f $0)
zm_workdir=${zm_path%/*}

SUDO=$(test "$(id -u)" = "0" || which sudo || true)

zm_version=0.02
zm_release=2


set -e 
set -E 

cd $zm_workdir

sfs_mpath=/media/sfs
unionfs_mpath=/media/unionfs
sfs_part_mpath=/media/sfsroot
sfs_root_mpath=$sfs_mpath/root
sfs_home_mpath=$sfs_mpath/home
unionfs_root_mpath=$unionfs_mpath/root
unionfs_home_mpath=$unionfs_mpath/home
unionfs_max_branch=8
unionfs_clean_file=.unionfs.fs.clean

KERNEL_VERSION=$(uname -r | awk  -F '-' 'BEGIN{OFS="."}{print $1}' | awk  -F '.' 'BEGIN{OFS="."}{print $1,$2,$3}')

zm_work_dir=/work
zm_backup_mpath=/media/backup
zm_backup_old_dir=${zm_backup_mpath}/old
zm_backup_dir=/media/bak



err()
{   
    echo "Error: $@"
    exit 1
}

show_version ()
{   
    echo "$zm_version"
    exit 0
}

backup_file()
{
    while [ $# -gt 0 ]; do
        bak_file=$1
        shift
        if [ -e "$bak_file" ];then
            bak_file_dir=$(dirname $bak_file)/old
            mkdir -p $bak_file_dir
            mv -fv ${bak_file} ${bak_file_dir}
        fi
    done
}

get_linux_kernel_code()  
{  
    #expr $(VERSION) \* 65536 + 0$(PATCHLEVEL) \* 256 + 0$(SUBLEVEL));  
    VERSION=`echo $1 | awk  -F '.' 'BEGIN{OFS="."}{print $1}'`  
    PATCHLEVEL=`echo $1 | awk  -F '.' 'BEGIN{OFS="."}{print $2}'`  
    SUBLEVEL=`echo $1 | awk  -F '.' 'BEGIN{OFS="."}{print $3}'`  
    #echo $VERSION  
    #echo $PATCHLEVEL  
    #echo $SUBLEVEL  
    KERNEL_CODE=`expr $VERSION \* 65536 + 0$PATCHLEVEL \* 256 + 0$SUBLEVEL` 
    echo $KERNEL_CODE  
}

download_file()
{
    src=$1
    dst=$2
    md5=$3
    DL="wget -c"

    if which axel;then
        if [ ! -e "$2" ];then
            axel $1 -o $2
        fi
    else
        wget -c $1 -O $2
    fi

    if [ -n "$md5" ];then
        echo "$md5 $dst" | md5sum -c 
    fi
}


select_continue_debconf ()
{
    echo "#!/bin/bash
    source $zm_workdir/common/init_debconf.sh
    db_reset zm_debconf/select_continue
    db_input high zm_debconf/select_continue
    db_go
    db_get zm_debconf/select_continue
    echo \$RET > $build_dir/dbconf_ret
    db_stop
    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf 2> /dev/null || true

    read ret_select < $build_dir/dbconf_ret
    if [ "$ret_select" = "false" ];then
        exit 1
    fi
}

select_continue()
{
    if [ "$zm_auto_select" = "yes" ];then
        return
    fi

    echo "$@ Continue? y/n"
    read input_char
    if [ "$input_char" !=  "y" ];then
        err "Select no and exit now."
    fi
}

get_free_mem_size_m()
{
    free -m | grep Mem | awk '{print $4}'
}

need_root()
{
    if [ "$(id -u)" != "0" ]; then
        err "This function must be run as root" 1>&2
    fi
}

_add_samba_user()
{
    user=$1
    passwd=$2
    echo -e "$passwd\n$passwd" | smbpasswd -a $user -s
}


usage ()
{
    declare -a options
    declare -a msgs
    index=0

    add_help()
    {
       options[$index]="$1"
       msgs[$index]="$2"
       index=$(expr $index + 1)
    }

    add_help "--install-grub device" "install grub on device, device like /dev/sda1"
    add_help "--install-system device" "install system on device, device like /dev/sda1"
    add_help "--arch arch" "system arch, value: i386|amd64"
    add_help "--deb-ver" "debian version, value: stable|testing|unstable"
    add_help "--gen-initrd [output_dir]" "generate initrd.img"
    add_help "--gen-iso-system iso_file_path" "install system to iso file"
    add_help "--build-dir dir" "build temp dir"
    add_help "-i, --install dir" "install zm to dir"
    add_help "-k, --keep-build" "Keep the temporary directory used to make the image."
    add_help "--chroot chroot_options" "like chroot options."
    add_help "--install-softs" "install softs."
    add_help "-m, --make-system [output dir]" "make system"
    add_help "--kernel-name" "kernel name"
    add_help "--kernel-ver" "kernel ver"
    add_help "--zm-dir" "zm system dir"
    add_help "--zm-user" "zm system user's name"
    add_help "--zm-userdir" "zm system user's config dir"
      
    echo "Usage:  <options>"
    for pos in $(seq 0 $(expr $index - 1))
    do
        option="${options[pos]}"
        msg="${msgs[pos]}"
        if [ ${#option} -gt 30 ];then
            printf "  %-30s  \n" "$option"
            printf "  %-30s : %-s\n" "" "$msg"
        else
            printf "  %-30s : %-s\n" "$option" "$msg"
        fi
    done
    return

    echo "
    --format-disk         format in disk
    --gen-usb-sfssystem   generate root.sfs and home.sfs to usb disk
    --download-softs      download softs
    --install-softs       install softs
    --setup
    -i, --install         install zm
    --version             Print version.
    --help                Print this help message.
    "
    exit 0
}

debug_var()
{
    var=$1
    eval value='$'$var
    printf "  %-15s : %-s\n" $var $value
}

print_line()
{
    num=80
    output_char='-'
    output_str=$(yes $output_char | head -$num | tr -d '\n')
    echo "$output_str"
}

print_env()
{
    print_line
    debug_var deb_ver
    debug_var kernel_name
    debug_var kernel_ver
    debug_var kernel_params 
    debug_var zm_arch
    debug_var zm_dir
    debug_var zm_user
    debug_var zm_user_dir
    debug_var install_dir
    debug_var apt_url
    debug_var build_dir
    for var in $@
    do
        debug_var $var
    done
    print_line
}

get_dir_res_space()
{
    # df -B1 $1 | awk '{print $4}' | /bin/grep '[[:digit:]]'
    false
}

get_freesize_dir_mb()
{
    # size_mb=$(df -mP $1 | sed -n '2p' | awk '{print $4}')
    # echo ${size_mb}
    false
}

get_usedsize_dir_mb()
{
    size_mb=$(du -ms $1 | awk '{print $1}')
    echo ${size_mb}
}

get_file_size()
{
    echo $(stat -c '%s' $1)
}

check_file_exist()
{
    test -z $1 && err "Please input check_file_exist() param"

    file=$1
    test -e $file || err "Cann't find file $file."
}

check_binary()
{
    if ! which $1 > /dev/null;then
        err "Not have $1."
    fi
}

rm_safe()
{
    dir=$1

    if [ ! -d "$dir" ];then
        return
    fi

    if [ $(get_usedsize_dir_mb "$dir") -gt 100 ];then
        select_continue "Directory($dir) have more data, please check again."
    fi
    rm -rf "$dir"
}

check_removeable_device()
{
    device=$1
    check_file_exist $device

    USBKEYS=($(
    grep -Hv ^0$ /sys/block/*/removable |
    sed s/removable:.*$/device\\/uevent/ |
    xargs grep -H ^DRIVER=sd |
    sed s/device.uevent.*$/size/ |
    xargs grep -Hv ^0$ |
    cut -d / -f 4
    ))
    echo $USBKEYS | grep -w $(basename $device) || err "$device is not remove disk"
}

print_disk_sizeinfo()
{
    if [ $# -gt 0 ];then
        fdisk -l $1 2>&1 | grep '^Disk /dev/.*:' | awk '{print $3$4}'
    fi
}

check_mount()
{
    cat /proc/mounts | grep "$1" > /dev/null
}

mount_device()
{
    last_param=${!#}
    if [ $# -gt 1 ];then
        $SUDO mount $@
    fi

    if [ ! -e $build_dir/.mount_devs ];then
        touch $build_dir/.mount_devs
    fi

    if grep "$last_param" $build_dir/.mount_devs > /dev/null;then
        echo "$last_param have mounted."
        return
    fi

    tmpfile=$build_dir/.mount_devs.temp
    (echo "$last_param" | cat - $build_dir/.mount_devs > $tmpfile) && mv $tmpfile $build_dir/.mount_devs
}

umount_device()
{
    if [ -e $build_dir/.mount_devs ];then
        $SUDO sh -c "cat /proc/mounts | grep $1 > /dev/null && umount $1 && sed -i \":^$1$:d\" $build_dir/.mount_devs || true"
    fi
}

sfs2dev()
{
    filename=$1
    device=$2
    restore_dir=$3

    echo -n "[ $FUNCNAME ] $filename -> $device "
    check_file_exist $filename
    check_file_exist $device

    mount_device $device $mnt_dir

    if [ ! -d $mnt_dir/$restore_dir ]; then 
        mkdir -p $mnt_dir/$restore_dir -m 0755
    fi
    sfs2dir $filename $mnt_dir/$restore_dir

    umount_device $mnt_dir
}

update_label()
{
    device=$1
    label=$2
    real_label=`e2label $device`
    if [ '$real_label' != '$label' ];then
        e2label $device $label
    fi
}

boot_log()
{
    debug_file=/run/initramfs/initramfs-debug
    if [ -e "$debug_file" ];then
        $EDITOR $debug_file
    fi
}

update_grub_config()
{
    sfsroot_dev=$(mount | grep -w /media/sfsroot | awk '{print $1}')
    select_continue "update grub on $sfsroot_dev"
    gen_default_grub_config $sfsroot_dev
}

defalut_install_dir()
{
    install_dir=$1
    if [ -z "$install_dir" -a $# = 2 ];then
        install_dir="$2"
    fi
    if [ -z "$install_dir" ];then
        install_dir=$zm_dir
        if [ ! -d $zm_dir ];then
            mkdir -p ${sfs_part_mpath}
            mount_device LABEL=sfsroot ${sfs_part_mpath}
        fi
    fi
    check_file_exist $install_dir
}

install_grub()
{
    grub_device=$1
    echo "[ $FUNCNAME ] grub -> $grub_device  "

    grub_device=$(readlink -f $grub_device)
    check_file_exist $grub_device

    select_continue "Install grub on $grub_device"

    #恢复主扇区
    #  /sbin/install-mbr $(echo ${grub_device} | tr -d [0-9])
    #激活扇区
    # sfdisk -A11 ${grub_device}

    mount_device $grub_device $mnt_dir
    install_grub_on_dir $mnt_dir
    if [ -e $mnt_dir/boot/grub/config/default.cfg ];then
        echo "Overwrite $mnt_dir/boot/grub/config/default.cfg ?"
        select_continue now
    fi
    grub-mkdevicemap -m $mnt_dir/boot/grub/device.map
    # mount_device --bind /dev $mnt_dir/dev
    # chroot $mnt_dir grub-mkconfig -o /boot/grub/grub.cfg
    # umount_device $mnt_dir/dev
    disk_device=${grub_device/p[0-9]*}
    if [ "$disk_device" == "$grub_device" ];then
        disk_device=${grub_device/[0-9]*}
    fi
    grub-install $disk_device --no-floppy --root-directory=$mnt_dir --modules="biosdisk part_msdos"
    umount_device $mnt_dir
}

install_grub_on_dir()
{
    install_dir=$1
    check_file_exist $install_dir
    if [ ! -d $install_dir/boot ];then
        $CP $sfs_part_mpath/boot $install_dir
    fi
    # mkdir -p $install_dir/boot/grub
    # $CP /usr/lib/grub/i386-pc $install_dir/boot/grub/
}

format_usb_device()
{
    usb_device=$1
    check_removeable_device $usb_device

    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    if check_mount $usb_device;then 
        err "$usb_device is mounted!"
    fi

    total_size=` fdisk -l $usb_device | grep Disk | awk '{print $5}'`
    total_cyln=`echo $total_size/255/63/512 | bc`

    diskinfo=` sfdisk -H 255 -S 63 -C $total_cyln -l $usb_device | grep Disk`
    cylns=`echo $diskinfo | awk '{print $3}'`
    heads=`echo $diskinfo | awk '{print $5}'`
    sectors=`echo $diskinfo | awk '{print $7}'`
    disksize=`echo "$cylns*$heads*$sectors*512" | bc`
    echo disksize = $disksize
    ext2_size_bytes=2500000000
    fat_cyln=`echo "($disksize-$ext2_size_bytes)/$heads/$sectors/512" | bc`
    fat_sectors=`echo "$fat_cyln*$heads*$sectors" | bc`
    echo fat_cyln = $fat_cyln
    echo fat_sectors = $fat_sectors

    echo -n " $usb_device size is "
    print_disk_sizeinfo $usb_device
    echo "Format $usb_device now?"
    select_continue now

    dd if=/dev/zero of=$usb_device bs=512 count=63
    sync;sleep 1;
    blockdev --rereadpt $usb_device
    sfdisk --label dos $usb_device -H 255 -S 63 -C $total_cyln << EOF
,$fat_cyln,0xc,*
,,0x83,-
EOF
    sync;sync;sync

    sleep 3;
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    if check_mount $usb_device;then 
        err "$usb_device is mounted!"
    fi

    blockdev --rereadpt $usb_device
    #  sfdisk -l $usb_device
    part1_dev=${usb_device}1
    part2_dev=${usb_device}2
    test -b $part1_dev || err "no part $part1_dev"
    test -b $part2_dev || err "no part $part2_dev"
    dd if=/dev/zero of=$part1_dev bs=512 count=1
    dd if=/dev/zero of=$part2_dev bs=512 count=1

    mkfs.vfat -n udisk $part1_dev
    mkfs.ext4 -L sfsroot_usb $part2_dev
    sync;sync;sync

    sleep 3;
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    umount "$usb_device"* > /dev/null 2>&1 || true
    if check_mount $usb_device;then 
        err "$usb_device is mounted!"
    fi
}

gen_iso_file()
{
    check_binary genisoimage

    iso_label="sfs_iso"
    iso_filename=$1

    install_grub_on_dir $iso_dir
    temp_path=/linux/$zm_arch/${zm_user}
    echo "
menuentry \"ZM($zm_arch) (default)\" --class debian {
set gfxpayload=keep
search --no-floppy -l --set=root $iso_label
echo 'Loading kernel...'
linux $temp_path/$kernel_name sfs_part=cdrom zm_user=$zm_user zm_arch=$zm_arch
echo 'Loading initrd...'
initrd $temp_path/$initrd_name
}
" > $iso_dir/boot/grub/grub.cfg

    #生成iso grub 引导file
    pushd .
    cd $iso_dir/boot/grub/i386-pc
    bootfile=g2hdr
    # grub-mkimage -O i386-pc -o core.img biosdisk ext2 fat iso9660
    grub-mkimage -O i386-pc -o core.img biosdisk iso9660
    cat /usr/lib/grub/i386-pc/cdboot.img core.img > ../$bootfile
    popd

    rm -f $iso_filename
    # “-b”后的文件路径不能是绝对路径，也不能是相对当前目录的路径，只能是相对于ISO源内容目录的路径。
    genisoimage -V $iso_label -R -J -no-emul-boot -boot-load-size 4 -boot-info-table -b boot/grub/$bootfile -o $iso_filename $iso_dir
}

mount_storage()
{
    mount_src=$1
    mount_point=$2
    $SUDO mkdir -p $mount_point
    $SUDO mount $mount_src $mount_point || err "mount $@ error"
}

umount_storage()
{
    mount_point=$1
    if [ -e "$mount_point" ];then
        $SUDO umount $mount_point || err "umount $@ error"
        if [ -d "$mount_point" ];then
            $SUDO rmdir $mount_point
        fi
    fi
}

__mount_with_aufs()
{
    sfsname="$1"
    sfsdir="$2"
    sfsmountdir=$3
    upperdir="$4"
    mountdir="$5"

    test -d "$upperdir" || err "upperdir: $upperdir is not found!"
    test -d "$mountdir" || err "mountdir: $mountdir is not found!"

    sfsfile=$(readlink -f "${sfsdir}/${sfsname}.sfs")
    test -f "$sfsfile" || err "sfsfile: ${sfsdir}/${sfsname}.sfs is not found!"

    if [ -e "${upperdir}/$unionfs_clean_file" ];then
        $SUDO rm -rf ${upperdir}/{*,.[!.]*,..?*}
    fi

    sfsmpath=$sfsmountdir/$sfsname
    mount_storage $sfsfile $sfsmpath
    $SUDO mount -t aufs -o br:$upperdir none $mountdir
    $SUDO mount -t aufs -o remount,udba=none,append:${sfsmpath}=ro none $mountdir

    for branch in $(seq 1 $unionfs_max_branch)
    do
        if [ -e "${sfsfile}.${branch}" ];then
            $SUDO mount_storage ${sfsfile}.${branch} ${sfsmpath}.${branch}
            $SUDO mount -t aufs -o remount,udba=none,add:1:${sfsmpath}.${branch}=ro+wh none $mountdir
            continue
        fi
        break
    done
}

__mount_with_overlay()
{
    sfsname="$1"
    sfsdir="$2"
    sfsmountdir=$3
    upperdir="$4"
    mountdir="$5"


    test -d "$upperdir" || err "upperdir: $upperdir is not found!"
    test -d "$mountdir" || err "mountdir: $mountdir is not found!"

    sfsfile=$(readlink -f "${sfsdir}/${sfsname}.sfs")
    test -f "$sfsfile" || err "sfsfile: ${sfsdir}/${sfsname}.sfs is not found!"

    if [ -e "${upperdir}/$unionfs_clean_file" ];then
        $SUDO rm -rf ${upperdir}/{*,.[!.]*,..?*}
    fi

    lowerdir=""
    set_lowerdir()
    {
        if [ -z "$lowerdir" ];then
            lowerdir=$@
        else
            lowerdir=$@:${lowerdir}
        fi
    }

    sfsmpath=$sfsmountdir/$sfsname
    mount_storage $sfsfile $sfsmpath
    for branch in $(seq 1 $unionfs_max_branch)
    do
        if [ -e "${sfsfile}.${branch}" ];then
            mount_storage ${sfsfile}.${branch} ${sfsmpath}.${branch}
            set_lowerdir ${sfsmpath}.${branch}
            continue
        fi
        break
    done

    set_lowerdir ${sfsmpath}
    debug_var $lowerdir

    $SUDO mkdir -p $upperdir/upper
    $SUDO mkdir -p $upperdir/work
    options="lowerdir=$lowerdir,upperdir=$upperdir/upper,workdir=$upperdir/work"
    $SUDO mount -t overlay -o $options overlay $mountdir
}

mount_unionfs()
{
    # sfsname sfsdir sfsmountdir upperdir mountdir

    if modprobe overlay > /dev/null 2>&1;then
        __mount_with_overlay $@
    elif modprobe aufs > /dev/null 2>&1;then
        __mount_with_aufs $@
    else
        err "no support union filesystem."
    fi
}

zm_build_deb_checkinstall() 
{
    which checkinstall > /dev/null 
    sudo checkinstall --pkgname zm --pkgversion $zm_version --pkgarch all \
        --pkgrelease "${zm_release}" --pkglicense GPL --maintainer 51feel@gmail.com \
        --requires "checkinstall,realpath,debootstrap,genisoimage,mbr,squashfs-tools" \
        -y --nodoc --deldesc=yes --delspec=yes --deldoc=yes --backup=no
    sudo dpkg -r zm
    sudo dpkg -i zm_${zm_version}-${zm_release}_all.deb
}

zm_build_deb_dhmake() 
{
    deb_dir=$build_dir/deb
    zm_git_url=$PWD
    mkdir $deb_dir
    git checkout $zm_git_url $deb_dir
    cd zm
}

zm_chroot()
{
    param1="$1"
    shift

    extension=${param1##*.}
    if [ "$extension" = "sfs" ];then
        sfsname=$(basename $param1)
        name=${sfsname//.*}
        sfsdir=$(dirname $param1)
        mount_device -t tmpfs -o mode=755 tmpfs $unionfs_dir
        # sfsname sfsdir sfsmountdir upperdir mountdir
        mount_unionfs $name $sfsdir $sfs_mnt_dir $unionfs_dir $root_dir
        mount_device $sfs_mnt_dir/$name
        mount_device $root_dir
        chroot_dir=$root_dir
    else
        chroot_dir=$(readlink -f "$param1")
    fi

    test -e $chroot_dir/bin/bash
    cp -fv /etc/resolv.conf $chroot_dir/etc/resolv.conf
    mount_device -t proc -o nosuid,noexec,nodev proc $chroot_dir/proc
    mount_device -t sysfs -o nosuid,noexec,nodev,ro sys $chroot_dir/sys
    mount_device -t devtmpfs -o mode=0755,nosuid udev $chroot_dir/dev
    mount_device -t devpts -o mode=0620,gid=5,nosuid,noexec devpts $chroot_dir/dev/pts
    mount_device -t tmpfs -o mode=1777,nosuid,nodev shm $chroot_dir/dev/shm
    mount_device -t tmpfs -o nosuid,nodev,mode=0755 run $chroot_dir/run
    mkdir -p $chroot_dir/run/lock
    if [ -d /work/cache/archives ];then
        mkdir -p $chroot_dir/var/cache/apt/archives
        mount_device --bind /work/cache/archives $chroot_dir/var/cache/apt/archives
    fi

    echo "chroot to $chroot_dir "
    SHELL=/bin/bash unshare --fork --pid chroot $chroot_dir $@

    chroot_process=$(lsof -t $chroot_dir) || true
    if [ -n "$chroot_process" ];then
       kill -9 $chroot_process
    fi

    if [ -d /work/cache/archives ];then
        umount_device $chroot_dir/var/cache/apt/archives
    fi
    umount_device $chroot_dir/run
    umount_device $chroot_dir/dev/shm
    umount_device $chroot_dir/dev/pts
    umount_device $chroot_dir/dev
    umount_device $chroot_dir/sys
    umount_device $chroot_dir/proc
}

get_kernel_file()
{
    if [ -z "$kernel_ver" ];then
        vmlinuz=$(readlink -f /vmlinuz)
    else
        vmlinuz=${kernel_name}-${kernel_ver}
    fi
    echo "$vmlinuz"
}

get_kernel_ver()
{
    ver=$kernel_ver
    if [ -z "$kernel_ver" ];then
        vmlinuz=$(get_kernel_file)
        ver=${vmlinuz#/boot/vmlinuz-}
    fi
    echo $ver
}

gen_kernel()
{
    defalut_install_dir $1
    vmlinuz=$(get_kernel_file)
    backup_file $install_dir/${kernel_name}
    /bin/cp -fv $vmlinuz $install_dir/${kernel_name}
}

gen_initrd()
{
    defalut_install_dir $1
    kernel_ver=$(get_kernel_ver)
    backup_file $install_dir/${initrd_name}
    echo "Genarate $install_dir/${initrd_name}..."
    mkinitramfs -d initramfs -o $install_dir/${initrd_name} $kernel_ver
}

gen_root_sfs()
{
    check_binary mksquashfs

    backup_file $2
    backup_file $2.[0-9]
    mksquashfs $1 $2 -comp lzo -regex \
        -e "lost+found" -e "sys/.*" -e "proc/.*" -e "run/.*" \
        -e "var/tmp/.*" -e "tmp/.*" \
        -e "media/.*" -e "mnt/.*" -e "dev/disk/.*/.*" \
        -e "etc/mtab" -e "etc/fstab" \
        -e "etc/udev/rules.d/70-.*net.*" \
        -e "etc/hal/fdi/policy/11-x11-vmmouse.fdi" \
        -e "etc/X11/xorg.conf*" \
        -e "usr/portage/distfiles/.*" \
        -e "usr/share/hal/fdi/policy/20thirdparty/11-x11-vmmouse.fdi" \
        -e "usr/bin/vmmouse_detect" \
        -e "var/cache/hald/fdi-cache" \
        -e "var/cache/apt/archives/.*" \
        -e "work/.*" \
        -e "home/.*/.*" 
    touch $1/$unionfs_clean_file_name
}

gen_home_sfs()
{
    check_binary mksquashfs

    backup_file $2
    backup_file $2.[0-9]
    mksquashfs $1 $2 -comp lzo -regex \
        -e ".*/.xauth*" -e ".*/.serverauth" \
        -e ".*/Downloads/.*" \
        -e ".*/.cache" \
        -e ".*/.backup/.*" \
        -e ".*/.xsession-errors" \
        -e ".*/.kermit.log" \
        -e ".*libreoffice.*" 
    touch $1/$unionfs_clean_file_name
}

update_system()
{
    need_root
    defalut_install_dir $1

    print_env

    # exec -a zm sh -c ""
    echo "#!/bin/bash
    source $zm_workdir/common/init_debconf.sh
    db_reset zm_debconf/sfsselect || true
    db_input high zm_debconf/sfsselect || true
    db_go || true
    db_get zm_debconf/sfsselect || true
    echo \$RET > $build_dir/dbconf_ret
    db_stop
    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf || true


    read sels < $build_dir/dbconf_ret
    # echo $sels

    select_continue_debconf

    IFS=', '
    for sel in $sels;do
        case $sel in
            kernel)
                gen_kernel $install_dir
                ;;
            initrd)
                gen_initrd $install_dir
                ;;
            root)
                gen_root_sfs / $install_dir/${root_sfs_name}
                ;;
            home)
                gen_home_sfs /home $install_dir/${home_sfs_name}
                ;;
            *)
                ;;
        esac
    done
}

branch_system()
{
    need_root
    defalut_install_dir
    sels="$1"
    if [ -z "$1" ];then
        sels="root home"
    fi
    for sel in $sels;do
        case $sel in
            root)
                for branch in $(seq 1 $unionfs_max_branch)
                do
                    if [ ! -e $install_dir/${root_sfs_name}.${branch} ];then
                        gen_root_sfs ${unionfs_root_mpath}/ $install_dir/${root_sfs_name}.$branch
                        break
                    fi
                done
                ;;
            home)
                for branch in $(seq 1 $unionfs_max_branch)
                do
                    if [ ! -e $install_dir/${home_sfs_name}.${branch} ];then
                        gen_home_sfs ${unionfs_home_mpath}/ $install_dir/${home_sfs_name}.$branch
                        break
                    fi
                done
                ;;
            *)
                ;;
        esac
    done
}

sfs2dir()
{
    7z x $1 -o${2}
}

gen_default_grub_config()
{
    grub_device=$1

    label_suffix=""
    disk_label=$(e2label $grub_device)
    if echo $disk_label | grep sfsroot;then
        label_suffix=${disk_label/sfsroot}
    fi
    if [ ! -z "$label_suffix" ];then
        kernel_params+=" label_suffix=$label_suffix"
    fi

    boot_uuid=$(blkid -s UUID $grub_device | awk -F= '{print $2}' | tr -d '"')
    temp_dir=$(mktemp -d)
    mount_device $grub_device $temp_dir
    temp_path=/linux/${zm_user}.${os_name}.${zm_arch}.${deb_ver}
    echo "
menuentry 'ZM linux $zm_user ($zm_arch)' --class=submenu --class debian {
    set root_uuid=$boot_uuid
    search --no-floppy --fs-uuid --set=root \$root_uuid
    set zm_dir=$temp_path
    echo 'Loading $zm_arch kernel...'
    linux \$zm_dir/${kernel_name} sfs_part=UUID=\$root_uuid $kernel_params 
    echo 'Loading $zm_arch initrd...'
    initrd \$zm_dir/${initrd_name}
}" > $temp_dir/boot/grub/config/default.cfg
    sed "s/\bzm\b/$zm_user/g" common/linux.cfg > $temp_dir/boot/grub/config/linux.cfg
    umount_device $temp_dir
    rmdir $temp_dir
}

gen_iso_system()
{
    iso_file=$1
    test -z "$iso_file" && err "iso file is null"
    install_system $iso_dir
    gen_iso_file $iso_file
}

gen_usb_boot ()
{
    usb_device=$1
    check_file_exist $usb_device

    grub_device=${usb_device}2
    if [ ! -b ${grub_device} ];then
        format_usb_device $usb_device
    fi
    check_file_exist $grub_device
    install_grub $grub_device
    gen_default_grub_config $grub_device
}

gen_usb_system()
{
    usb_device=$1
    check_file_exist $usb_device

    if [ ! -b ${usb_device}2 ];then
        format_usb_device $usb_device
    else 
        disk_id=$(sfdisk --print-id $usb_device 2)
        if [ $disk_id != 83 ];then
            format_usb_device $usb_device
        fi
    fi
    usb_root_device=${usb_device}2
    check_file_exist $usb_root_device

    install_system $usb_root_device 
}

create_virtual_disk()
{
    check_binary install-mbr 

    disk_format=qcow2
    # disk_format=vdi
    # disk_format=vmdk

    root_file=/tmp/zm_root.$disk_format
    work_file=/tmp/zm_work.$disk_format
    root_size=32G
    work_size=64G

    if [ -e "$root_file" ];then
        select_continue "$root_file exists, delete it?"
        rm -f $root_file
    fi
    if [ -e "$work_file" ];then
        select_continue "$work_file exists, delete it?"
        rm -f $work_file
    fi

    print_env root_file work_file root_size work_size disk_format

    select_continue "Create $disk_format virtual disk [$root_file] [$work_file]."
    zm_auto_select="yes"

    if [ ! -e "$root_file" ];then
        qemu-img create -f $disk_format "$root_file" "$root_size"
    fi
    if [ ! -e "$work_file" ];then
        qemu-img create -f $disk_format "$work_file" "$work_size"
    fi
    qemu-nbd -d /dev/nbd0 || true
    qemu-nbd -d /dev/nbd1 || true
    rmmod nbd || true
    modprobe nbd max_part=16
    qemu-nbd --cache writeback -c /dev/nbd0 $root_file
    qemu-nbd --cache writeback -c /dev/nbd1 $work_file
    # qemu-nbd --cache writethrough -c /dev/nbd0 $root_file
    install-mbr --force /dev/nbd0
    install-mbr --force /dev/nbd1

    parted -s -a optimal /dev/nbd0 mklabel msdos
    parted -s -a optimal /dev/nbd0 mkpart primary ext2 64s 100%
    parted -s -a optimal /dev/nbd1 mklabel msdos
    parted -s -a optimal /dev/nbd1 mkpart primary ext2 64s 100%

    while [ ! -e /dev/nbd0p1 ];do
        blockdev --rereadpt /dev/nbd0
        sleep 1
    done
    while [ ! -e /dev/nbd1p1 ];do
        blockdev --rereadpt /dev/nbd1
        sleep 1
    done
    mkfs.ext4 -L sfsroot /dev/nbd0p1
    mkfs.ext4 -L work /dev/nbd1p1

    install_system /dev/nbd0p1

    qemu-nbd -d /dev/nbd0
    qemu-nbd -d /dev/nbd1

    chmod 777 $root_file
    chmod 777 $work_file

    echo ""
    echo "kvm -m 2048 -hda $root_file -hdb $work_file"
    echo "kvm -m 1024 -hda $root_file"
    echo ""
}

default_zm_setup()
{
    echo "change root password..."
    echo root:'root' | chpasswd
}

auto_install()
{
    # export DEBIAN_FRONTEND=gnome
    export DEBIAN_FRONTEND=noninteractive

    install_zm
    install_softs

    zm_user_command zm_setup

    gen_kernel /media/install
    gen_initrd /media/install
    gen_root_sfs / /media/install/${root_sfs_name}
    # gen_home_sfs /home /media/install/${home_sfs_name}

    sync;sync;sync
}

make_system()
{
    need_root
    check_binary debootstrap

    print_env

    if [ ! -e "$root_dir/bin/sh" ];then
        if [ -d /work/cache/archives ];then
            mkdir -p $root_dir/var/cache/apt/archives
            mount_device --bind /work/cache/archives $root_dir/var/cache/apt/archives
        fi
        debootstrap --arch $zm_arch ${deb_ver} $root_dir $apt_url/debian
        if [ -d /work/cache/archives ];then
            umount_device $root_dir/var/cache/apt/archives
        fi
    fi

    $zm_path --zm-user $zm_user --zm-userdir $zm_user_dir --install $root_dir/tmp/ 

    mkdir -p $zm_dir
    mkdir -p $root_dir/media/install
    mount_device --bind $zm_dir $root_dir/media/install

    if $zm_debug;then
        zm_chroot $root_dir "/tmp/zm --debug --zm-user $zm_user --deb-ver $deb_ver --arch $zm_arch auto_install"
    else
        zm_chroot $root_dir "/tmp/zm --zm-user $zm_user --deb-ver $deb_ver --arch $zm_arch auto_install"
    fi

    umount_device $root_dir/media/install
}

install_system()
{
    dst=$1

    check_file_exist $root_sfs_file

    if [ "${dst_dir:0:4}" = '/dev' ];then
        if [ ! -b $dst ];then
            err "$dst_dir is not block file."
        fi
    fi
    if [ -b $dst ];then
        mount_device $dst $root_dir
        dst_dir=$root_dir
        install_grub $dst
        gen_default_grub_config $dst
    else
        dst_dir=$dst
        mkdir -p $dst_dir
    fi

    temp_dir=$dst_dir/linux/$zm_arch/$zm_user
    mkdir -p $temp_dir

    $CP $zm_dir/${kernel_name} $temp_dir
    $CP $zm_dir/${initrd_name} $temp_dir
    # gen_initrd $dst_dir/linux/$zm_arch/

    rsync -avP $root_sfs_file $temp_dir
    rsync -avP $root_sfs_file.[0-9] $temp_dir || true
    if [ -e $home_sfs_file ];then
        rsync -avP $home_sfs_file $temp_dir
        rsync -avP $home_sfs_file.[0-9] $temp_dir || true
    fi

    $zm_path --install $root_dir/zm

    sync;sync;sync

    # md5sum $temp_dir/${root_sfs_name}
    # md5sum $temp_dir/${initrd_name}

    if [ -b $dst ];then
        umount_device $dst_dir
    fi
}

add_soft()
{	
    echo "$@" >> $soft_list_file
}

mount_apt_cache()
{
    if mount | grep /work/cache/archives > /dev/null;then
        return
    fi
    if [ -d /work/cache/archives ];then
        mount --bind /work/cache/archives /var/cache/apt/archives
    fi
}

apt_update()
{
    echo "Testing internet connect status..."
    # nc -v -w 3 www.baidu.com -z 80
    nc -w 3 www.baidu.com -z 80

    mount_apt_cache

    if [ $zm_arch = "amd64" ];then
        dpkg --add-architecture i386
    fi

    if [ ! -e /tmp/.zm_apt_update ];then
	echo "update system..."
        $APTGET update
        touch /tmp/.zm_apt_update
    fi
}

default_zm_setup_apt()
{
    temp_apt_src_file=$build_dir/sources.list
    > $temp_apt_src_file
    echo "deb $apt_url/debian $deb_ver main non-free contrib" >> $temp_apt_src_file
    echo "deb-src $apt_url/debian $deb_ver main non-free contrib" >> $temp_apt_src_file
    if [ "$deb_ver" != "unstable" ];then
        echo "deb $apt_url/debian $deb_ver-updates main non-free contrib" >> $temp_apt_src_file
        echo "deb $apt_url/debian $deb_ver-backports main non-free contrib" >> $temp_apt_src_file
        echo "deb $apt_url/debian-security/ $deb_ver/updates main non-free contrib" >> $temp_apt_src_file
        echo "deb-src $apt_url/debian $deb_ver-updates main non-free contrib" >> $temp_apt_src_file
        echo "deb-src $apt_url/debian $deb_ver-backports main non-free contrib" >> $temp_apt_src_file
        echo "deb-src $apt_url/debian-security/ $deb_ver/updates main non-free contrib" >> $temp_apt_src_file
    fi
    if ! diff $temp_apt_src_file /etc/apt/sources.list > /dev/null 2>&1;then
        mv $temp_apt_src_file /etc/apt/sources.list
    fi
}

add_base_softs()
{
    case $zm_arch in
        amd64)
            kernel_softs="linux-image-amd64 linux-headers-amd64"; 
            ;;
        *)
            kernel_softs="linux-image-686-pae linux-headers-686-pae"; 
            ;;
    esac

    add_soft locales 
    add_soft "$kernel_softs"
    add_soft grub2 udev procinfo
    add_soft initramfs-tools aptitude lsof
    add_soft acpi-support acpi
    add_soft hdparm usbutils lshw 
    add_soft module-init-tools dosfstools exfat-utils ntfs-3g busybox genisoimage mbr 
    add_soft iproute realpath gpm rsync util-linux gpart debootstrap pciutils 
    add_soft e2fsprogs squashfs-tools aufs-tools 
    add_soft lftp less bc
    add_soft ssh openssh-server nfs-common 
    add_soft vim gzip xz-utils 
    add_soft network-manager 
    # pigz lzip plzip pxz p7zip-full
}


download_softs()
{
    add_base_softs
    zm_user_command zm_add_softs
    zm_user_command zm_setup_apt
    apt_update

    _download_soft()
    {
        echo ">>>> download $@"
        apt-get -q --no-install-recommends --no-install-suggests --yes install -d -m $@
    }
    if $zm_debug;then
        cat $soft_list_file | while read line; do _download_soft $line; done
    else
        _download_soft $(cat $soft_list_file)
    fi
}

install_softs()
{
    print_env

    download_softs

    $APTGET upgrade || true

    _install_soft()
    {
        echo ">>>> install $@"
        $APTGET install $@
    }

    cat $soft_list_file | while read line; do _install_soft $line; done

    apt-get -y autoremove || true
}

dump_depends()
{
    softs=$(cat $soft_list_file)
    for deb in $softs
    do
        apt-cache -i depends $deb
        # apt-cache --no-suggests depends $deb
    done
    $SUDO apt-get install apt-rdepends
    apt-rdepends -d $softs > /tmp/dep.dot
    cat /tmp/dep.dot | less
    rm /tmp/dep.dot
}

zm_user_command()
{
    cmd=$1
    shift
    test -z "$cmd" && return
    if command -v $cmd > /dev/null 2>&1;then
        $cmd $*
        return
    fi

    def_cmd="default_$cmd"
    test -z "$def_cmd" && return
    if command -v $def_cmd > /dev/null 2>&1;then
        $def_cmd $*
    fi
}

zm_add_groups()
{
    groups="$@"
    for g in $groups
    do
        if ( grep $g /etc/group > /dev/null; ) && ! ( groups $zm_user | grep $g > /dev/null; );then
            usermod -a -G $g $zm_user
        fi
    done
}

install_zm()
{
    install_dir=$1
    if [ -z "$install_dir" ];then
        install_dir="/usr/share/zm"
    fi
    mkdir -p $install_dir
    $CP $zm_workdir/{zm,zm_debconf.templates,common,initramfs,mbak,user} $install_dir

    user_install_dir=$(readlink -m $install_dir/user/$zm_user)
    if [ "$zm_user_dir" != "$user_install_dir" ];then
        rm_safe $user_install_dir
        mkdir -p $user_install_dir
        $CP -fv $zm_user_dir/. $user_install_dir/
    fi

    if [ $install_dir = "/usr/share/zm" ];then
        ln -sf $install_dir/zm /usr/bin/zm
    fi

    echo "install zm to $install_dir"
}

zm_setup_tzdata() 
{
    area=$1
    zone=$2
    echo "#!/bin/bash
    . $zm_workdir/common/init_debconf.sh

    rm -f /etc/localtime
    rm -f /etc/timezone
    db_set tzdata/Areas '$area' || true
    db_set tzdata/Zones/$area '$zone' || true
    db_fset tzdata/Areas seen true || true
    db_fset tzdata/Zones/$area seen true || true

    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -u tzdata || true
}

zm_setup_sh()
{
    default_shell=$1

    case "$default_shell" in
        bash) 
            echo "#!/bin/bash
            . $zm_workdir/common/init_debconf.sh
            db_set dash/sh 'false' || true
            db_fset dash/sh seen true || true
            " > $build_dir/zm_debconf
            ;;
        dash)
            echo "#!/bin/bash
            . $zm_workdir/common/init_debconf.sh
            db_set dash/sh 'true' || true
            db_fset dash/sh seen true || true
            " > $build_dir/zm_debconf
            ;;
        *)
            return
            ;;
    esac

    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf

    dpkg-reconfigure -u dash || true
}

zm_setup_default_locales()
{
    rm -f /etc/locale.gen

    echo "#!/bin/bash
    . $zm_workdir/common/init_debconf.sh

    db_set locales/locales_to_be_generated 'en_US.UTF-8 UTF-8, zh_CN.GBK GBK, zh_CN.UTF-8 UTF-8'
    db_subst locales/default_environment_locale locales 'en_US.UTF-8, zh_CN.GBK, zh_CN.UTF-8'
    db_set locales/default_environment_locale 'en_US.UTF-8'
    db_fset locales/default_environment_locale seen true
    db_fset locales/locales_to_be_generated seen true

    " > $build_dir/zm_debconf
    chmod +x $build_dir/zm_debconf
    $CP zm_debconf.templates $build_dir/
    $build_dir/zm_debconf

    dpkg-reconfigure -u locales || true
}

zm_mount_backup()
{
    if [ -z "$@" ];then
        return
    fi

    $SUDO mount | grep $zm_backup_mpath > /dev/null 2>&1 || return

    bak_name="$1"
    bak_root_dir=$zm_backup_dir/$bak_name
    bak_unionfs_dir=$zm_backup_mpath/unionfs/$bak_name
    if ! readlink -e $bak_root_dir > /dev/null 2>&1;then
        $SUDO rmdir $bak_root_dir > /dev/null 2>&1 || true
    fi
    if [ ! -e $bak_root_dir ];then
        $SUDO mkdir -m 700 -p $bak_root_dir
        $SUDO mkdir -m 700 -p $bak_unionfs_dir

        # __mount_with_unionfs $bak_name $zm_backup_mpath $sfs_mpath $bak_unionfs_dir $bak_root_dir
        mount_unionfs $bak_name $zm_backup_mpath $sfs_mpath $bak_unionfs_dir $bak_root_dir
        if [ $? != 0 ];then
            echo "mount unionfs error"
            $SUDO rmdir $bak_root_dir
            return 1
        fi

        $SUDO chown $UID $bak_unionfs_dir
        $SUDO chown $UID $bak_root_dir
    fi

    if [ -L $zm_work_dir/$bak_name ];then
        bak_work_dir=$(readlink -e $zm_work_dir/$bak_name)
        if [ "$bak_work_dir" = "$bak_root_dir" ];then
            echo $zm_work_dir/$bak_name 
            return 0
        else
            rm -vf $zm_work_dir/$bak_name
        fi
    fi

    if [ -e $zm_work_dir/$bak_name ];then
        echo $bak_root_dir
        return 0
    fi

    ln -s $bak_root_dir $zm_work_dir/$bak_name 
    echo $zm_work_dir/$bak_name 
}

zm_check_backup()
{
    bak_params=$@
    if [ -z "$@" ];then
        bak_params='.'
    fi

    $SUDO mount | grep $sfs_mpath/$bak_name > /dev/null 2>&1 || return 1
    $SUDO mount | grep $unionfs_dir_dir/$bak_name > /dev/null 2>&1 || return 1
    # echo $bak_root_dir | grep $(readlink -e $PWD) > /dev/null && cd
    return 0
}

zm_umount_backup()
{
    bak_params=$1
    if [ -z "$1" ];then
        bak_params='.'
    fi

    $SUDO mount | grep $zm_backup_mpath > /dev/null 2>&1 || return

    if [ ! -e $zm_backup_dir ];then
        echo "zm backup dir is not exist."
        return 1
    fi

    for bak_name in $bak_params
    do

        if [ -z $bak_name -o "$bak_name" = '..' ];then
            echo "param error."
            return 0
        fi

        if [ $bak_name = '.' ];then
            bak_name=$(basename $(readlink -e $bak_name))
        fi

        umount_storage $zm_backup_dir/$bak_name 

        bak_zm_sfs_dir=$sfs_mpath/$bak_name
        for branch in $(seq 1 $unionfs_max_branch)
        do
            branch_sfs_mount_dir=${bak_zm_sfs_dir}.${branch}
            if [ -d "$branch_sfs_mount_dir" ];then
                umount_storage $branch_sfs_mount_dir
                continue
            fi
            break
        done  

        umount_storage $bak_zm_sfs_dir 

        if [ -L $zm_work_dir/$bak_name ];then
            bak_work_dir=$(readlink -e $zm_work_dir/$bak_name)
            if [ "$bak_work_dir" !=  "$bak_root_dir" ];then
                rm -vf $zm_work_dir/$bak_name
            fi
        fi

    done
}



test_stable()
{
    echo "test"    
}

zm_argv_del()
{
    if [ -n "$1" ];then
        # zm_argv=${zm_argv/"$1"}
        zm_argv=$(echo " "$zm_argv" " | sed -e "s# $1 # #g" | xargs)
    fi
}

zm_config()
{
    
    while [ $# -gt 0 ]; do
        case $1 in
            --root-sfs) zm_argv_del $1;shift; root_sfs_name=$1; zm_argv_del $1;shift; 
                ;;
            --home-sfs) zm_argv_del $1;shift; home_sfs_name=$1; zm_argv_del $1;shift; 
                ;;
            --initrd) zm_argv_del $1;shift; initrd_name=$1; zm_argv_del $1;shift; 
                ;;
            --kernel-name) zm_argv_del $1;shift; kernel_name=$1; zm_argv_del $1;shift; 
                ;;
            --kernel-ver) zm_argv_del $1;shift; kernel_ver=$1; zm_argv_del $1;shift; 
                ;;
            --zm-user) zm_argv_del $1;shift; zm_user=$1; zm_argv_del $1;shift;
                ;;
            --zm-userdir) zm_argv_del $1;shift; zm_user_dir=$1; zm_argv_del $1;shift;
                ;;
            --zm-dir) zm_argv_del $1;shift; zm_dir=$1; zm_argv_del $1;shift;
                ;;
            --arch) zm_argv_del $1;shift; zm_arch=$1; zm_argv_del $1;shift;
                ;;
            --apt-url) zm_argv_del $1;shift; apt_url="$1"; zm_argv_del "$1";shift;
                ;;
            --deb-ver) zm_argv_del $1;shift; deb_ver=$1; zm_argv_del $1;shift;
                ;;
            --yes|-y) zm_argv_del $1;shift; zm_auto_select="yes";
                ;;
            --build-dir) zm_argv_del $1;shift; build_dir=$1; zm_argv_del $1;shift;
                ;;
            --keep-build|-k) zm_argv_del $1;shift; keep_build_dir="yes";
                ;;
            --kernel-params) zm_argv_del $1;shift; kernel_params="$1"; zm_argv_del $1;shift;
                ;;
            --debug) zm_argv_del $1;shift; zm_debug=true;
                ;;
            *) shift; 
                ;;
      esac
  done

  if $zm_debug;then
      set -x
      CP='/bin/cp -rafv'
  fi

  if [ -z "$build_dir" ];then
      if $zm_debug;then
          build_dir=/tmp/zm_build
          mkdir -p $build_dir
      else
          #can use TMPDIR change, see man mktemp
          build_dir=$(mktemp -d)
      fi
  fi

  test -d "$build_dir" || err "build_dir ($build_dir) isn't dir."
  if [ $(get_usedsize_dir_mb "$build_dir") -gt 5000 ];then
      select_continue "build dir($build_dir) have more data, please check again."
  fi

  mnt_dir=$build_dir/mnt
  iso_dir=$build_dir/iso
  sfs_mnt_dir=$build_dir/sfs
  unionfs_dir=$build_dir/unionfs
  root_dir=$build_dir/root
  dl_dir=$build_dir/dl

  soft_list_file=$build_dir/soft_list
  > $build_dir/soft_list


  mkdir -p $mnt_dir
  mkdir -p $iso_dir
  mkdir -p $sfs_mnt_dir
  mkdir -p $unionfs_dir
  mkdir -p $root_dir
  mkdir -p $dl_dir

  #trap zm_uninit ERR INT QUIT TERM EXIT
  trap zm_uninit ERR INT TERM EXIT

  if [ -z "$zm_user" ];then
      if [ -z "$SUDO_USER" ];then
          zm_user=$USER
      else
          zm_user=$SUDO_USER
      fi
  fi

  if [ -z "$zm_dir" ];then
      zm_dir=$sfs_part_mpath/linux/$zm_arch
      if [ -d "$zm_dir/$zm_user" ];then
          zm_dir="$sfs_part_mpath/linux/$zm_arch/$zm_user"
      fi
      os_name="debian"
      zm_dir=$sfs_part_mpath/linux/${zm_user}.${os_name}.${zm_arch}.${deb_ver}
  fi
  root_sfs_file=$zm_dir/${root_sfs_name}
  home_sfs_file=$zm_dir/${home_sfs_name}
  kernel_file=$zm_dir/${kernel_name}
  initrd_file=$zm_dir/${initrd_name}

  zm_user_home=$(grep $zm_user /etc/passwd | awk -F:  '{print $6}')
  if [ -z "$zm_user_dir" ];then
      if [ -d $zm_user_home/.zm ];then
          zm_user_dir=$zm_user_home/.zm
      else
          if [ -d $zm_workdir/user/$zm_user ];then
              zm_user_dir=$zm_workdir/user/$zm_user
          fi
      fi
  fi
  check_file_exist "$zm_user_dir"
  zm_user_dir=$(readlink -f $zm_user_dir)

  if [ -e $zm_user_dir/config.sh ];then
      source $zm_user_dir/config.sh
  fi

  zm_user_command zm_user_init


  if [ -z "$kernel_params" ];then
      if $zm_debug;then
          kernel_params="debug"
      else
          kernel_params="quiet"
      fi
  fi
}

zm_excute()
{
    while [ $# -gt 0 ]; do
        case $1 in
            --install-grub) shift; install_grub $1; test -z "$1" || shift; 
                ;;
            --install-system) shift; install_system $1; test -z "$1" || shift; 
                ;;
            --make-system) shift; make_system; exit 0;
                ;;
            --gen-kernel) shift; gen_kernel $1; test -z "$1" || shift; 
                ;;
            --gen-initrd) shift; gen_initrd $1; test -z "$1" || shift; 
                ;;
            --gen-root) shift; gen_root_sfs / $1/${root_sfs_name}; test -z "$1" || shift; 
                ;;
            --gen-home) shift; gen_home_sfs /home $1/${home_sfs_name}; test -z "$1" || shift; 
                ;;
            --branch-system|-b) shift; branch_system $1; test -z "$1" || shift; 
                ;;
            --gen-iso-system) shift; gen_iso_system $1; test -z "$1" || shift; 
                ;;
            --gen-usb-system) shift; gen_usb_system $1; test -z "$1" || shift; 
                ;;
            --gen-usb-boot) shift; gen_usb_boot $1; test -z "$1" || shift;
                ;;
            --download-softs|-d) download_softs; shift;
                ;;
            --install-softs) install_softs; shift
                ;;
            --debconf-softs) zm_user_command debconf_softs; shift 
                ;;
            --setup) zm_user_command zm_setup; shift
                ;;
            --update-system|-u) shift; update_system $1; test -z "$1" || shift; 
                ;;
            --install|-i) shift; install_zm $1; test -z "$1" || shift
                ;;
            --edit|-e) $EDITOR $zm_path; exit 0;
                ;;
            --chroot) shift; zm_chroot $@; exit 0;
                ;;
            --build-deb) shift; zm_build_deb_dhmake $1; exit 0;
                ;;
            --mount-backup) shift; zm_mount_backup $@; exit 0;
                ;;
            --umount-backup) shift; zm_umount_backup $@; exit 0;
                ;;
            --version)
                show_version; exit 0;
                ;;
            *) 
                echo "$1"
                type -t "$1" > /dev/null && { echo "run $1";$1; }; shift
                ;;
        esac
    done
}

zm_init()
{
    CP='/bin/cp -raf'
    # aptitude -d -R -y install 
    # APTGET='apt-get --yes'
    # APTGET='apt-get --no-install-recommends --no-install-suggests --yes'
	    APTGET='apt-get --no-install-recommends --no-install-suggests --yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew'
    if ! $zm_debug;then
	    APTGET+=' -qq'
    fi

    cpu_counts=`cat /proc/cpuinfo | grep "processor" | wc -l`

    GZ=gzip
    LZ=lzip
    XZ=xz

    which pigz > /dev/null 2>&1 && GZ="pigz -p $cpu_counts"
    which plzip > /dev/null 2>&1 && LZ="plzip -n $cpu_counts"
    which pxz > /dev/null 2>&1 && XZ="pxz -T$cpu_counts"


    root_sfs_name="root.sfs"
    home_sfs_name="home.sfs"
    initrd_name="initrd.img"
    kernel_name="vmlinuz"
    kernel_ver=""
    kernel_params=""

    zm_dir=""
    zm_user=""
    zm_user_dir=""

    build_dir=""
    keep_build_dir="no"

    # deb_ver=testing
    deb_ver=$(cat /etc/apt/sources.list | awk '{print $3}' | head -1)
    if [ "$deb_ver" != "stable" -o "$deb_ver" != "unstable" -o "$deb_ver" != "testing" ];then
        deb_ver="stable"
    fi

    zm_arch=$(dpkg --print-architecture)

    # no multimedia
    # apt_url=http://mirrors.163.com
    apt_url=http://mirrors.aliyun.com
    # apt_url=http://mirrors.sohu.com

    # have multimedia
    # apt_url=http://free.nchc.org.tw
    # apt_url=http://mirrors.ustc.edu.cn
    # apt_url=http://mirrors.xmu.edu.cn
    # apt_url=http://mirror.bjtu.edu.cn

    zm_auto_select="no"

    code_kernel_3_18=$(get_linux_kernel_code 3.18.0)
    code_kernel_now=$(get_linux_kernel_code $KERNEL_VERSION)
    #echo $code_kernel_3_18 $code_kernel_now
}

zm_uninit()
{
    if $zm_debug;then
        set +x
        print_env
    fi
    trap - ERR INT TERM EXIT
    if [ -d "$build_dir" ];then
        if $zm_debug;then
            echo "$zm_path $zm_argv Clean ..."
        fi
        if [ -e $build_dir/.mount_devs ];then
            devs=`cat $build_dir/.mount_devs`
            for dev in $devs;do
                umount_device $dev || true
            done
            rm -rf $build_dir/.mount_devs
        fi
        if $zm_debug;then
            echo "In debug mode, please manual delete $build_dir"
        else
            if [ "$keep_build_dir" != "yes" ];then
                if [ $(get_usedsize_dir_mb "$build_dir") -gt 5000 ];then
                    select_continue "build dir($build_dir) have more data, please check again."
                fi
                rm -rf $build_dir 
            fi
        fi
    fi
}

###############################################################################
###############################################################################
###############################################################################

if [ $# -eq 0 -o "$1" = "--help" ];then
    usage
    exit 0
fi

zm_argv=$@
zm_clean=true
zm_debug=false

export zm_debug

zm_init
zm_config $zm_argv
zm_excute $zm_argv
zm_uninit


