#!/bin/sh

deb_arch=$1

case $deb_arch in
    amd64)
        kernel_softs="linux-image-amd64 linux-headers-amd64"; 
        ;;
    *)
        kernel_softs="linux-image-686-pae linux-headers-686-pae"; 
        ;;
esac

zm_base_softs="$kernel_softs grub2 aptitude vim nfs-common udev procinfo 
    hdparm e2fsprogs usbutils lftp less lshw bc initramfs-tools ssh openssh-server
    module-init-tools dosfstools exfat-utils ntfs-3g busybox genisoimage mbr 
    iproute realpath gpm rsync util-linux gpart debootstrap pciutils 
    gzip squashfs-tools aufs-tools locales network-manager"

# pigz lzip plzip xz-utils pxz p7zip-full

export DEBIAN_FRONTEND=noninteractive 
APTGET='apt-get --no-install-recommends --no-install-suggests --yes -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew'
$APTGET update
$APTGET upgrade
$APTGET install $zm_base_softs

/tmp/zm --install 
/tmp/zm --gen-initrd /tmp
echo root:root | chpasswd

sync;sync;sync
